volumes:
  db-data:

services:
  app:
    build:
      context: .
      # args:
      #   RUBY_VERSION:
      #   BUNDLE_PATH:
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: tail -f /dev/null
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.3
    ports:
      - 5432:5432
    env_file:
      - db/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 2s
      timeout: 1s
      retries: 10
